/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softgym;

import Utilidades.usadb;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ErickFrancisco
 */
public class morosos extends javax.swing.JInternalFrame {

    /**
     * Creates new form morosos
     */
    public morosos() {
        initComponents();
        usadb db=new usadb();
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        Date hoy=new Date();
        Date iniciodelostiempos=new Date(); iniciodelostiempos.setYear(0);
        Object[][] clienmor=db.get_fechaCorteClientes(new Object[]{iniciodelostiempos,hoy}, "fechacorte");
        
        for(int i=0;clienmor!=null&&i<clienmor.length;i++){
            Object[][] cliente=db.get_cliente(clienmor[i][0], "idcliente");
            Object[][] pagos=db.get_historialPagoClientes(clienmor[i][0], "idcliente");
            Object[][] ingreso=db.get_ingresos(pagos[pagos.length-1][1], "idIngresos");
            System.out.println( pagos[pagos.length-1][1] );
            
            System.out.println(( (Date)ingreso[0][1]).toLocaleString() );
            dtm.addRow(new Object[]{
                cliente[0][1],
                clienmor[i][1],
                ((Date)ingreso[0][1]).toLocaleString().substring(0, 11)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes con pagos atrasados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Fecha Corte", "Fecha ult/pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
